version: '3.8'
services:
  factorio:
    build: .

    container_name: factorio

    ports:
      - "34197:34197/udp"

    restart: unless-stopped

    environment:
      ADMINLIST: ${ADMINLIST}
      WHITELIST: ${WHITELIST}
      SERVER_NAME: ${SERVER_NAME-Name}
      SERVER_DESC: ${SERVER_NAME-Description}
      MAX_PLAYER: ${MAX_PLAYER-0}
      VISIBILITY_PUBLIC: ${VISIBILITY_PUBLIC-false}
      VISIBILITY_LAN: ${VISIBILITY_LAN-true}
      FACTORIO_USERNAME: ${FACTORIO_USERNAME?Missing username. Add a .env file}
      FACTORIO_TOKEN: ${FACTORIO_TOKEN?Missing token. Add a .env file}
      REQUIRE_USER_VERIFICATION: ${REQUIRE_USER_VERIFICATION-true}
      MAX_UPLOAD_KBPS: ${MAX_UPLOAD_KBPS-0}
      MAX_UPLOAD_SLOT: ${MAX_UPLOAD_SLOT-5}
      MINIMUM_LATENCY: ${MINIMUM_LATENCY-0}
      IGNORE_LIMIT_FOR_RETURNING_PLAYERS: ${IGNORE_LIMIT_FOR_RETURNING_PLAYERS-false}
      ALLOW_COMMANDS: ${ALLOW_COMMANDS-admins-only}
      AUTOSAVE_INTERVAL: ${AUTOSAVE_INTERVAL-10}
      AUTOSAVE_SLOTS: ${AUTOSAVE_SLOTS-5}
      AFK_KICK_INTERVAL: ${AFK_KICK_INTERVAL-0}
      AUTO_PAUSE: ${AUTO_PAUSE-true}
      ONLY_ADMINS_CAN_PAUSE: ${ONLY_ADMINS_CAN_PAUSE-true}
      AUTOSAVE_ONLY_SERVER: ${AUTOSAVE_ONLY_SERVER-true}
      NON_BLOCKING_SAVE: ${NON_BLOCKING_SAVE-false}
      MIN_SEGMENT_SIZE: ${MIN_SEGMENT_SIZE-25}
      MIN_SEGMENT_SIZE_PEER_COUNT: ${MIN_SEGMENT_SIZE_PEER_COUNT-20}
      MAX_SEGMENT_SIZE: ${MAX_SEGMENT_SIZE-100}
      MAX_SEGMENT_SIZE_PEER_COUNT: ${MAX_SEGMENT_SIZE_PEER_COUNT-10}

    volumes:
      - ./server-settings.json.tmpl:/server-settings.json.tmpl
      - factorioData:/factorio

    entrypoint: /bin/bash -c "exec /entrypoint.sh"

volumes:
  factorioData:
    driver: local
